### ISSUE TITLE
App not working for new users

### ISSUE THREAD

**Issue by KunalSheengada** [KunalSheengada/ToDo_JS#1]
Keys are not being generated for the first time when the program runs.

**Comment by deepak-sourcecode** [comment]
Could you please elaborate on this? I tried this and works fine on my browser.

**Comment by KunalSheengada** [comment]
> Could you please elaborate on this? I tried this and works fine on my browser.

I have made the necessary changes in the code. It is working fine now. Issue was with the windows.onload function in the JS file. It was not generating the key in the local storage for the first time used on any system and breaking the code.
